#!/usr/bin/env python
"""Update notebook cells with fallback data generation."""
import json

with open('notebooks/00_data_exploration.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# --- Cell 2: Imports with fallback generator ---
nb['cells'][2]['source'] = [
    'import pandas as pd\n',
    'import numpy as np\n',
    'import matplotlib.pyplot as plt\n',
    'import warnings\n',
    'import time\n',
    'import random\n',
    'warnings.filterwarnings("ignore")\n',
    '\n',
    '# --- 尝试导入 akshare ---\n',
    'try:\n',
    '    import akshare as ak\n',
    '    HAS_AKSHARE = True\n',
    'except ImportError:\n',
    '    HAS_AKSHARE = False\n',
    '    print("⚠ akshare 未安装，将使用模拟数据")\n',
    '\n',
    '# --- 中文字体配置 ---\n',
    'plt.rcParams["font.sans-serif"] = ["SimHei", "Microsoft YaHei", "DejaVu Sans"]\n',
    'plt.rcParams["axes.unicode_minus"] = False\n',
    'plt.rcParams["figure.dpi"] = 100\n',
    'plt.rcParams["savefig.dpi"] = 150\n',
    'np.random.seed(42)\n',
    'random.seed(42)\n',
    '\n',
    '# --- 模拟数据生成器 ---\n',
    'def generate_index_data(days=1500, start_price=3500):\n',
    '    """生成逼真的沪深300走势"""\n',
    '    dates = pd.date_range("2021-01-04", periods=days, freq="B")\n',
    '    # 模拟真实走势\n',
    '    returns = np.zeros(days)\n',
    '    # 2021:震荡 - 2022:熊市 - 2023:反弹 - 2024:震荡 - 2025:横盘\n',
    '    for i in range(days):\n',
    '        if i < 250:   trend = -0.0001\n',
    '        elif i < 500: trend = -0.0008\n',
    '        elif i < 750: trend = -0.0003\n',
    '        elif i < 1000:trend = 0.0003\n',
    '        elif i < 1250:trend = 0.0001\n',
    '        else:         trend = -0.00005\n',
    '        returns[i] = trend + 0.012 * np.random.randn()\n',
    '    # 偶尔的极端行情\n',
    '    shock_idx = np.random.choice(days, size=40, replace=False)\n',
    '    for idx in shock_idx:\n',
    '        magnitude = np.random.uniform(0.015, 0.04)\n',
    '        returns[idx] = magnitude if np.random.random() > 0.6 else -magnitude\n',
    '    close = start_price * np.exp(np.cumsum(returns))\n',
    '    open_p = close * (1 + np.random.randn(days) * 0.003)\n',
    '    high = np.maximum(open_p, close) * (1 + np.abs(np.random.randn(days) * 0.005))\n',
    '    low = np.minimum(open_p, close) * (1 - np.abs(np.random.randn(days) * 0.005))\n',
    '    volume = np.abs(np.random.randn(days) * 1e8 + 2e8).astype(int)\n',
    '    amount = volume * close * 0.01\n',
    '    return pd.DataFrame({\n',
    '        "date": dates, "open": open_p.round(2), "close": close.round(2),\n',
    '        "high": high.round(2), "low": low.round(2),\n',
    '        "volume": volume, "amount": amount\n',
    '    })\n',
    '\n',
    'def generate_stock_data(base_close, days=1200, beta=1.0, vol=0.025):\n',
    '    """生成个股数据，与指数有 beta 相关性"""\n',
    '    dates = base_close.index[-days:]\n',
    '    index_ret = base_close.pct_change().dropna().iloc[-(days-1):].values\n',
    '    stock_ret = beta * index_ret + np.random.normal(0, vol, len(index_ret))\n',
    '    stock_close = 100 * np.exp(np.cumsum(stock_ret))\n',
    '    return pd.Series(stock_close, index=dates[-len(stock_close):], name="close")\n',
    '\n',
    '# --- 网络容错 ---\n',
    'def fetch_with_retry(func, name, max_retries=3, base_delay=3):\n',
    '    """带重试的数据获取"""\n',
    '    for attempt in range(1, max_retries + 1):\n',
    '        try:\n',
    '            print(f"  正在获取 {name} ...", end=" ")\n',
    '            result = func()\n',
    '            print("OK")\n',
    '            return result\n',
    '        except Exception as e:\n',
    '            delay = base_delay * (2 ** (attempt - 1))\n',
    '            if attempt < max_retries:\n',
    '                print(f"失败({type(e).__name__})，{delay}s 后重试...")\n',
    '                time.sleep(delay)\n',
    '            else:\n',
    '                print(f"失败({type(e).__name__})")\n',
    '                raise\n',
    '\n',
    'print(f"pandas {pd.__version__}  |  numpy {np.__version__}")\n',
    'print(f"akshare: {"可用" if HAS_AKSHARE else "不可用，使用模拟数据"}")\n',
]

# --- Cell 4: CSI 300 data with fallback ---
nb['cells'][4]['source'] = [
    '# 获取沪深300指数日线数据（自动降级：在线 → 离线模拟）\n',
    'print("拉取沪深300指数数据：")\n',
    'DATA_SOURCE = "未知"\n',
    '\n',
    'if HAS_AKSHARE:\n',
    '    try:\n',
    '        df_index = fetch_with_retry(\n',
    '            lambda: ak.stock_zh_index_daily_em(symbol="sh000300"),\n',
    '            name="沪深300日线"\n',
    '        )\n',
    '        DATA_SOURCE = "akshare 在线数据"\n',
    '    except Exception as e:\n',
    '        print(f"  akashare 不可用，使用本地模拟数据")\n',
    '        df_index = generate_index_data()\n',
    '        DATA_SOURCE = "本地模拟(沪深300历史波动特征)"\n',
    'else:\n',
    '    df_index = generate_index_data()\n',
    '    DATA_SOURCE = "本地模拟(沪深300历史波动特征)"\n',
    '\n',
    'print(f"数据来源: {DATA_SOURCE}")\n',
    'print(f"数据形状: {df_index.shape}")\n',
    'print(f"时间范围: {df_index.date.min()} ~ {df_index.date.max()}")\n',
    'df_index.head(10)\n',
]

# --- Cell 16: Stock data with fallback ---
nb['cells'][16]['source'] = [
    '# 拉取几只代表性个股的日线数据（失败自动降级为模拟）\n',
    'stocks = {\n',
    '    "贵州茅台": {"code": "600519", "beta": 0.95, "vol": 0.022},\n',
    '    "宁德时代": {"code": "300750", "beta": 1.35, "vol": 0.032},\n',
    '    "招商银行": {"code": "600036", "beta": 1.05, "vol": 0.020},\n',
    '    "比亚迪":   {"code": "002594", "beta": 1.25, "vol": 0.030},\n',
    '    "中国平安": {"code": "601318", "beta": 0.90, "vol": 0.022},\n',
    '}\n',
    '\n',
    'close_prices = pd.DataFrame()\n',
    '\n',
    'for name, cfg in stocks.items():\n',
    '    fetched = False\n',
    '    if HAS_AKSHARE:\n',
    '        try:\n',
    '            df_stock = fetch_with_retry(\n',
    '                lambda c=cfg["code"]: ak.stock_zh_a_hist(symbol=c, period="daily",\n',
    '                    start_date="20210101", end_date="20250620", adjust="qfq"),\n',
    '                name=f"{name}({cfg[chr(34)+chr(34)]})"\n',
    '            )\n',
    '            df_stock["日期"] = pd.to_datetime(df_stock["日期"])\n',
    '            df_stock = df_stock.set_index("日期")\n',
    '            close_prices[name] = df_stock["收盘"]\n',
    '            fetched = True\n',
    '            print(f"  {name}: akshare ({len(df_stock)}条)")\n',
    '        except Exception as e:\n',
    '            print(f"  {name}: akshare不可用 → 模拟")\n',
    '    if not fetched:\n',
    '        base = df_index.set_index("date")["close"]\n',
    '        close_prices[name] = generate_stock_data(base, beta=cfg["beta"], vol=cfg["vol"])\n',
    '\n',
    'print(f"\\n成功: {len(close_prices.columns)}/{len(stocks)} 只股票, 形状: {close_prices.shape}")\n',
    'close_prices.head()\n',
]

# Fix the f-string issue in cell 16 source (the {cfg["code"]} part)
# Actually let me just write the cell correctly from the start
nb['cells'][16]['source'] = [
    '# 拉取几只代表性个股的日线数据（失败自动降级为模拟）\n',
    'stocks = {\n',
    '    "贵州茅台": {"code": "600519", "beta": 0.95, "vol": 0.022},\n',
    '    "宁德时代": {"code": "300750", "beta": 1.35, "vol": 0.032},\n',
    '    "招商银行": {"code": "600036", "beta": 1.05, "vol": 0.020},\n',
    '    "比亚迪":   {"code": "002594", "beta": 1.25, "vol": 0.030},\n',
    '    "中国平安": {"code": "601318", "beta": 0.90, "vol": 0.022},\n',
    '}\n',
    '\n',
    'close_prices = pd.DataFrame()\n',
    '\n',
    'for name, cfg in stocks.items():\n',
    '    code, beta_val, vol_val = cfg["code"], cfg["beta"], cfg["vol"]\n',
    '    fetched = False\n',
    '    if HAS_AKSHARE:\n',
    '        try:\n',
    '            df_stock = fetch_with_retry(\n',
    '                lambda c=code: ak.stock_zh_a_hist(symbol=c, period="daily",\n',
    '                    start_date="20210101", end_date="20250620", adjust="qfq"),\n',
    '                name=f"{name}({code})"\n',
    '            )\n',
    '            df_stock["日期"] = pd.to_datetime(df_stock["日期"])\n',
    '            df_stock = df_stock.set_index("日期")\n',
    '            close_prices[name] = df_stock["收盘"]\n',
    '            fetched = True\n',
    '            print(f"  {name}: akshare ({len(df_stock)}条)")\n',
    '        except Exception as e:\n',
    '            print(f"  {name}: akshare不可用 转为模拟")\n',
    '    if not fetched:\n',
    '        base = df_index.set_index("date")["close"]\n',
    '        close_prices[name] = generate_stock_data(base, beta=beta_val, vol=vol_val)\n',
    '\n',
    'print(f"\\n成功: {len(close_prices.columns)}/{len(stocks)} 只股票, 形状: {close_prices.shape}")\n',
    'close_prices.head()\n',
]

with open('notebooks/00_data_exploration.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("Done: notebook updated with fallback data generation")
